global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "order-api"
    static_configs:
      - targets: ["host.docker.internal:19100"]

  - job_name: "user-rpc"
    static_configs:
      - targets: ["host.docker.internal:19101"]

  - job_name: "product-rpc"
    static_configs:
      - targets: ["host.docker.internal:19102"]

  - job_name: "order-rpc"
    static_configs:
      - targets: ["host.docker.internal:19103"]
