// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package server

import (
	"context"

	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/product/internal/logic"
	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/product/internal/svc"
	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/product/productpb"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	productpb.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) GetProduct(ctx context.Context, in *productpb.GetProductRequest) (*productpb.GetProductResponse, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductServer) ReserveStock(ctx context.Context, in *productpb.ReserveStockRequest) (*productpb.ReserveStockResponse, error) {
	l := logic.NewReserveStockLogic(ctx, s.svcCtx)
	return l.ReserveStock(in)
}
