// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package order

import (
	"context"

	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/order/orderpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderRequest  = orderpb.CreateOrderRequest
	CreateOrderResponse = orderpb.CreateOrderResponse
	GetOrderRequest     = orderpb.GetOrderRequest
	GetOrderResponse    = orderpb.GetOrderResponse
	OrderItem           = orderpb.OrderItem

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := orderpb.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := orderpb.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}
