// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rpc/user/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_rpc_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_rpc_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CheckUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserStatusRequest) Reset() {
	*x = CheckUserStatusRequest{}
	mi := &file_rpc_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserStatusRequest) ProtoMessage() {}

func (x *CheckUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUserStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserStatusResponse) Reset() {
	*x = CheckUserStatusResponse{}
	mi := &file_rpc_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserStatusResponse) ProtoMessage() {}

func (x *CheckUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUserStatusResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CheckUserStatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_rpc_user_user_proto protoreflect.FileDescriptor

const file_rpc_user_user_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/user/user.proto\x12\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"t\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"1\n" +
	"\x16CheckUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"G\n" +
	"\x17CheckUserStatusResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x8e\x01\n" +
	"\x04User\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12N\n" +
	"\x0fCheckUserStatus\x12\x1c.user.CheckUserStatusRequest\x1a\x1d.user.CheckUserStatusResponseB\n" +
	"Z\b./userpbb\x06proto3"

var (
	file_rpc_user_user_proto_rawDescOnce sync.Once
	file_rpc_user_user_proto_rawDescData []byte
)

func file_rpc_user_user_proto_rawDescGZIP() []byte {
	file_rpc_user_user_proto_rawDescOnce.Do(func() {
		file_rpc_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_user_user_proto_rawDesc), len(file_rpc_user_user_proto_rawDesc)))
	})
	return file_rpc_user_user_proto_rawDescData
}

var file_rpc_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_user_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),          // 0: user.GetUserRequest
	(*GetUserResponse)(nil),         // 1: user.GetUserResponse
	(*CheckUserStatusRequest)(nil),  // 2: user.CheckUserStatusRequest
	(*CheckUserStatusResponse)(nil), // 3: user.CheckUserStatusResponse
}
var file_rpc_user_user_proto_depIdxs = []int32{
	0, // 0: user.User.GetUser:input_type -> user.GetUserRequest
	2, // 1: user.User.CheckUserStatus:input_type -> user.CheckUserStatusRequest
	1, // 2: user.User.GetUser:output_type -> user.GetUserResponse
	3, // 3: user.User.CheckUserStatus:output_type -> user.CheckUserStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_user_user_proto_init() }
func file_rpc_user_user_proto_init() {
	if File_rpc_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_user_user_proto_rawDesc), len(file_rpc_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_user_user_proto_goTypes,
		DependencyIndexes: file_rpc_user_user_proto_depIdxs,
		MessageInfos:      file_rpc_user_user_proto_msgTypes,
	}.Build()
	File_rpc_user_user_proto = out.File
	file_rpc_user_user_proto_goTypes = nil
	file_rpc_user_user_proto_depIdxs = nil
}
