// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: compute.proto

package computepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DistributedCompute_Process_FullMethodName = "/compute.DistributedCompute/Process"
)

// DistributedComputeClient is the client API for DistributedCompute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistributedComputeClient interface {
	// 客户端流式发送数据 → 服务端实时计算 → 流式返回结果
	Process(ctx context.Context, opts ...grpc.CallOption) (DistributedCompute_ProcessClient, error)
}

type distributedComputeClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributedComputeClient(cc grpc.ClientConnInterface) DistributedComputeClient {
	return &distributedComputeClient{cc}
}

func (c *distributedComputeClient) Process(ctx context.Context, opts ...grpc.CallOption) (DistributedCompute_ProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &DistributedCompute_ServiceDesc.Streams[0], DistributedCompute_Process_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &distributedComputeProcessClient{stream}
	return x, nil
}

type DistributedCompute_ProcessClient interface {
	Send(*ComputeTask) error
	Recv() (*ComputeResult, error)
	grpc.ClientStream
}

type distributedComputeProcessClient struct {
	grpc.ClientStream
}

func (x *distributedComputeProcessClient) Send(m *ComputeTask) error {
	return x.ClientStream.SendMsg(m)
}

func (x *distributedComputeProcessClient) Recv() (*ComputeResult, error) {
	m := new(ComputeResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DistributedComputeServer is the server API for DistributedCompute service.
// All implementations must embed UnimplementedDistributedComputeServer
// for forward compatibility
type DistributedComputeServer interface {
	// 客户端流式发送数据 → 服务端实时计算 → 流式返回结果
	Process(DistributedCompute_ProcessServer) error
	mustEmbedUnimplementedDistributedComputeServer()
}

// UnimplementedDistributedComputeServer must be embedded to have forward compatible implementations.
type UnimplementedDistributedComputeServer struct {
}

func (UnimplementedDistributedComputeServer) Process(DistributedCompute_ProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedDistributedComputeServer) mustEmbedUnimplementedDistributedComputeServer() {}

// UnsafeDistributedComputeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributedComputeServer will
// result in compilation errors.
type UnsafeDistributedComputeServer interface {
	mustEmbedUnimplementedDistributedComputeServer()
}

func RegisterDistributedComputeServer(s grpc.ServiceRegistrar, srv DistributedComputeServer) {
	s.RegisterService(&DistributedCompute_ServiceDesc, srv)
}

func _DistributedCompute_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DistributedComputeServer).Process(&distributedComputeProcessServer{stream})
}

type DistributedCompute_ProcessServer interface {
	Send(*ComputeResult) error
	Recv() (*ComputeTask, error)
	grpc.ServerStream
}

type distributedComputeProcessServer struct {
	grpc.ServerStream
}

func (x *distributedComputeProcessServer) Send(m *ComputeResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *distributedComputeProcessServer) Recv() (*ComputeTask, error) {
	m := new(ComputeTask)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DistributedCompute_ServiceDesc is the grpc.ServiceDesc for DistributedCompute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributedCompute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compute.DistributedCompute",
	HandlerType: (*DistributedComputeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _DistributedCompute_Process_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "compute.proto",
}
