// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package product

import (
	"context"

	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/product/productpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProductRequest    = productpb.GetProductRequest
	GetProductResponse   = productpb.GetProductResponse
	ReserveStockRequest  = productpb.ReserveStockRequest
	ReserveStockResponse = productpb.ReserveStockResponse

	Product interface {
		GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
		ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	client := productpb.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

func (m *defaultProduct) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	client := productpb.NewProductClient(m.cli.Conn())
	return client.ReserveStock(ctx, in, opts...)
}
