global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-api"
    static_configs:
      - targets: ["user-api:9091"]

  - job_name: "user-rpc"
    static_configs:
      - targets: ["user-rpc:9092"]

  - job_name: "order-api"
    static_configs:
      - targets: ["order-api:9093"]

  - job_name: "order-rpc"
    static_configs:
      - targets: ["order-rpc:9094"]
