// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/order/internal/logic"
	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/order/internal/svc"
	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/order/orderpb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	orderpb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) CreateOrder(ctx context.Context, in *orderpb.CreateOrderRequest) (*orderpb.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) GetOrder(ctx context.Context, in *orderpb.GetOrderRequest) (*orderpb.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}
