// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateOrderReq struct {
	UserId int64          `json:"user_id"`
	Items  []OrderItemReq `json:"items"`
}

type CreateOrderResp struct {
	OrderId     string  `json:"order_id"`
	Status      string  `json:"status"`
	TotalAmount float64 `json:"total_amount"`
}

type GetOrderReq struct {
	OrderId string `path:"order_id"`
}

type GetOrderResp struct {
	OrderId     string  `json:"order_id"`
	UserId      int64   `json:"user_id"`
	Status      string  `json:"status"`
	TotalAmount float64 `json:"total_amount"`
}

type OrderItemReq struct {
	ProductId int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}
