// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/user/internal/logic"
	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/user/internal/svc"
	"iotestgo/module06_gozero/project_ecommerce_standard/rpc/user/userpb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *userpb.GetUserRequest) (*userpb.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) CheckUserStatus(ctx context.Context, in *userpb.CheckUserStatusRequest) (*userpb.CheckUserStatusResponse, error) {
	l := logic.NewCheckUserStatusLogic(ctx, s.svcCtx)
	return l.CheckUserStatus(in)
}
