// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatRoom_Subscribe_FullMethodName    = "/chat.ChatRoom/Subscribe"
	ChatRoom_SendMessages_FullMethodName = "/chat.ChatRoom/SendMessages"
	ChatRoom_Chat_FullMethodName         = "/chat.ChatRoom/Chat"
)

// ChatRoomClient is the client API for ChatRoom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatRoomClient interface {
	// 服务端流：客户端发一次请求，服务端持续推送消息
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ChatRoom_SubscribeClient, error)
	// 客户端流：客户端持续发送消息，服务端最后返回确认
	SendMessages(ctx context.Context, opts ...grpc.CallOption) (ChatRoom_SendMessagesClient, error)
	// 双向流：双方独立读写，全双工通信
	Chat(ctx context.Context, opts ...grpc.CallOption) (ChatRoom_ChatClient, error)
}

type chatRoomClient struct {
	cc grpc.ClientConnInterface
}

func NewChatRoomClient(cc grpc.ClientConnInterface) ChatRoomClient {
	return &chatRoomClient{cc}
}

func (c *chatRoomClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ChatRoom_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatRoom_ServiceDesc.Streams[0], ChatRoom_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatRoomSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatRoom_SubscribeClient interface {
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatRoomSubscribeClient struct {
	grpc.ClientStream
}

func (x *chatRoomSubscribeClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatRoomClient) SendMessages(ctx context.Context, opts ...grpc.CallOption) (ChatRoom_SendMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatRoom_ServiceDesc.Streams[1], ChatRoom_SendMessages_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatRoomSendMessagesClient{stream}
	return x, nil
}

type ChatRoom_SendMessagesClient interface {
	Send(*ChatMessage) error
	CloseAndRecv() (*SendSummary, error)
	grpc.ClientStream
}

type chatRoomSendMessagesClient struct {
	grpc.ClientStream
}

func (x *chatRoomSendMessagesClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatRoomSendMessagesClient) CloseAndRecv() (*SendSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatRoomClient) Chat(ctx context.Context, opts ...grpc.CallOption) (ChatRoom_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatRoom_ServiceDesc.Streams[2], ChatRoom_Chat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatRoomChatClient{stream}
	return x, nil
}

type ChatRoom_ChatClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatRoomChatClient struct {
	grpc.ClientStream
}

func (x *chatRoomChatClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatRoomChatClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatRoomServer is the server API for ChatRoom service.
// All implementations must embed UnimplementedChatRoomServer
// for forward compatibility
type ChatRoomServer interface {
	// 服务端流：客户端发一次请求，服务端持续推送消息
	Subscribe(*SubscribeRequest, ChatRoom_SubscribeServer) error
	// 客户端流：客户端持续发送消息，服务端最后返回确认
	SendMessages(ChatRoom_SendMessagesServer) error
	// 双向流：双方独立读写，全双工通信
	Chat(ChatRoom_ChatServer) error
	mustEmbedUnimplementedChatRoomServer()
}

// UnimplementedChatRoomServer must be embedded to have forward compatible implementations.
type UnimplementedChatRoomServer struct {
}

func (UnimplementedChatRoomServer) Subscribe(*SubscribeRequest, ChatRoom_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedChatRoomServer) SendMessages(ChatRoom_SendMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessages not implemented")
}
func (UnimplementedChatRoomServer) Chat(ChatRoom_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatRoomServer) mustEmbedUnimplementedChatRoomServer() {}

// UnsafeChatRoomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatRoomServer will
// result in compilation errors.
type UnsafeChatRoomServer interface {
	mustEmbedUnimplementedChatRoomServer()
}

func RegisterChatRoomServer(s grpc.ServiceRegistrar, srv ChatRoomServer) {
	s.RegisterService(&ChatRoom_ServiceDesc, srv)
}

func _ChatRoom_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatRoomServer).Subscribe(m, &chatRoomSubscribeServer{stream})
}

type ChatRoom_SubscribeServer interface {
	Send(*ChatMessage) error
	grpc.ServerStream
}

type chatRoomSubscribeServer struct {
	grpc.ServerStream
}

func (x *chatRoomSubscribeServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatRoom_SendMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatRoomServer).SendMessages(&chatRoomSendMessagesServer{stream})
}

type ChatRoom_SendMessagesServer interface {
	SendAndClose(*SendSummary) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatRoomSendMessagesServer struct {
	grpc.ServerStream
}

func (x *chatRoomSendMessagesServer) SendAndClose(m *SendSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatRoomSendMessagesServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatRoom_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatRoomServer).Chat(&chatRoomChatServer{stream})
}

type ChatRoom_ChatServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatRoomChatServer struct {
	grpc.ServerStream
}

func (x *chatRoomChatServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatRoomChatServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatRoom_ServiceDesc is the grpc.ServiceDesc for ChatRoom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatRoom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatRoom",
	HandlerType: (*ChatRoomServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ChatRoom_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendMessages",
			Handler:       _ChatRoom_SendMessages_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _ChatRoom_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
